### ISSUE TITLE
TEsNumberEdit component raises exception in mdi app

### ISSUE THREAD

**Issue by rcarrillom** [TurboPack-XE8/Essentials#1]
The TEsNumberEdit component raises exception in mdi app when then mdichild form is closed and its Panel was displayed, if the panel of TEsNumberEdit is never displayed, the exception is not triggered.

The source line where the exception is raised is
EsCalc.pas:1297  if not cPanel.HandleAllocated then

After the OnClose event of the mdichild is finished, the procedure TEsCustomCalculator.WMGetTextLength is called is some point in the code execution after the destructor TEsCustomCalculator.Destroy has been completed.

**Comment by romankassebaum** [comment]
Do you have a small demo app?

**Comment by rcarrillom** [comment]
I'm using D10 Seattle, You can reproduce this behaviour creating a new Delphi project: File | New | Other, then Delphi projects, choose MDI Application. After you get the new blank project with the two default Units, drop a TEsCustomCalculator on the mdichildren, run the project, then click the New button, once the mdi is created, close it, nothing happends, create a new one, popup the Calculator Panel, then close it and close the mdi form, an exception will raises. I added to the project a second new blank mdi child form, same exception. 

As a quick fix, I added the next line of code at the beggining of WMGetTextLength
`if not Assigned(cPanel) then Exit;`

**Comment by romankassebaum** [comment]
I could reproduce the issue and added

if cPanel = nil then
    Exit;

You can find the code under

https://github.com/TurboPack/Essentials

The XE8 branch is only for XE8.
